# Generated by Django 6.1.1 on 2026-09-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=150)),
                ('type_contrat', models.CharField(choices=[('alternance', 'Alternance'), ('stage', 'Stage')], default='none', max_length=20)),
                ('lien_annonce', models.URLField(blank=True, null=True)),
                ('date_envoie', models.DateField()),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('relancee', 'Relanée'), ('entretien', 'Entretien programé'), ('refusee', 'Refusée'), ('acceptée', 'Acceptée')], default='envoyee', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
