# Generated by Django 6.1.1 on 2026-09-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='candidatures',
            new_name='candidature',
        ),
    ]
