# Generated by Django 6.1.1 on 2026-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0002_rename_candidatures_candidature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='type_contrat',
            field=models.CharField(choices=[('alternance', 'Alternance'), ('stage', 'Stage'), ('non_precise', 'Non précisé')], default='non_precise', max_length=20),
        ),
    ]
