# Generated by Django 6.1.1 on 2026-09-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0003_alter_candidature_type_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
